### ISSUE TITLE
Client generation fails for JSON objects containing validation keyword "maximum"

### ISSUE THREAD

**Issue by gurumeditator** [atomicbits/scraml#110]
Client generation fails with "Cannot parse unknown type" if the JSON schema contains the validation keyword "maximum":

```
"value": {
   "maximum": 4294967295,
   "minimum": 0,
   "type": "integer"
}
```
Scraml 0.5.1b

**Comment by rigolepe** [comment]
Looking into it...

**Comment by rigolepe** [comment]
"maximum" is not an integer value (it is too long), but a long and de new parser doesn't consider the Long type. It's an easy fix. I will try to get 0.5.2 out with the fix very soon.

**Comment by rigolepe** [comment]
0.5.2 is released an should be available in public repositories soon

**Comment by gurumeditator** [comment]
Thanks for the quick fix Peter!
