### ISSUE TITLE
error: not found: value scramlVersion

### ISSUE THREAD

**Issue by partounian** [atomicbits/scraml#137]
Sorry this is basically my first time ever using Scala, I wrote some raml docs that display fine as html, and want to test them with Scraml. 
However, this line `addSbtPlugin("io.atomicbits" %% "scraml-dsl-play25-scala" % scramlVersion.value)` throw the error `error: not found: value scramlVersion`. I would replace that with a hardcoded value, but I'm not sure what to replace that with?

**Comment by rigolepe** [comment]
Hello Patrick,

Thanks for trying scraml! The latest version is 0.6.1, for a quick guide
see http://scraml.io/scaladocumentation/#_quickstart_scala

Best regards,
   Peter

Op ma 29 mei 2017 08:10 schreef Patrick Artounian <notifications@github.com
