### ISSUE TITLE
Parse Failure for JSON List Includes

### ISSUE THREAD

**Issue by ian-speers** [atomicbits/scraml#144]
The parser fails when the RAML source contains JSON includes consisting of a top level list. Failure case demonstrated [here](https://github.com/atomicbits/scraml/pull/142), and a proposed fix is available [here](https://github.com/atomicbits/scraml/pull/143). Please let me know if there are any questions, comments, etc. Happy to follow up with changes as requested. Thanks!

**Comment by ian-speers** [comment]
[fix](https://github.com/atomicbits/scraml/pull/143) was merged

**Comment by rigolepe** [comment]
Released in 0.7.1.

**Comment by ian-speers** [comment]
Thanks!
