### ISSUE TITLE
JSON schema using reserved Java words and special characters

### ISSUE THREAD

**Issue by jepatel** [atomicbits/scraml#45]
Was playing around with Scraml (working great so far) and ran into the following issues when generating the Java client:

1.  Enums in JSON that have start with a number or have special characters, or use reserved words (" ", /, "new", etc) generate invalid Java.

2.  Schema IDs with special characters generate invalid package name (e.g "hello-world" will generate a package "hello-world).

**Comment by rigolepe** [comment]
Glad you like scraml so far. Replacing special characters has been taken into account on many places already, but clearly not everywhere. I'll look into the problems you mention later today and fix them. I think they cause similar problems in the scala client.

**Comment by jepatel** [comment]
Thanks! Does Scraml work with RAML 1.0 is it is just 0.8 right now?

**Comment by rigolepe** [comment]
We're still on RAML 0.8, but we're working on integration with 1.0. The people at Mulesoft are finishing a native java RAML parser for 1.0 that will replace the javascript-wrapper version that is currently on github. We'll use that new parser as soon as it is published.

**Comment by rigolepe** [comment]
I released scraml 0.4.6, which should fix the issues that you mentioned about enum names and schema IDs with special characters.

**Comment by jepatel** [comment]
Thanks!  Any chance we could chat over email?  We're planning building RAML spec'ed services and wanted to learn more about your plans with Scraml.  My email is jeson.patel@gmail.com.
