### ISSUE TITLE
Gradle integration

### ISSUE THREAD

**Issue by rigolepe** [atomicbits/scraml#51]

**Comment by mozinrat** [comment]
Hi Team, With lots of appreciation for your work, just want to check if the gradle integration is still in your release plans.

**Comment by rigolepe** [comment]
Hello,

It certainly is on our release plan. We're now working on the more complex issues related to RAML 1.0 (union types, overlays, extensions and libraries). The next step is supporting more platforms and the first will be Android specific codegen. And with Android support, we plan to work on gradle integration. 

We don't expect gradle support to be a large issue, so it may be worth taking it in between if it is an important feature for a lot of people...

**Comment by rigolepe** [comment]
Gradle integration was pulled up the priority list, there is a first milestone release ready on the 0.7 version releases, see: https://github.com/atomicbits/scraml/blob/develop/documentation/javadocumentation.adoc#quickstart-java-using-gradle

The test project is here: https://github.com/atomicbits/scraml-test-java-gradle 

Let us know how it works and what we can improve.
