### ISSUE TITLE
Scraml uses its own RAML parser to facilitate RAML 1.0 support

### ISSUE THREAD

**Issue by rigolepe** [atomicbits/scraml#62]

**Comment by Regner** [comment]
Any update on progress for this? Would love a nice utility for generating Scala clients.

**Comment by rigolepe** [comment]
The new parser is ready and being tested. The progress now is on integrating the parser into the scraml code generation module. As soon as this is ready, I'll release a 0.5.0.beta version that can be tested by people who already use scraml today. This version will be able to parse basic RAML 1.0 types and of course json-schema as before. More exotic RAML 1.0 functionality like union types will not yet be supported. That's the next step, together with supporting RAML resource types.

**Comment by Regner** [comment]
Thank you very much for the update. :)
