### ISSUE TITLE
Date-time JSON Schema support

### ISSUE THREAD

**Issue by gurumeditator** [atomicbits/scraml#63]
Schema objects of type string containing the date-time format parameter are serialized as Java String objects. Are there plans to support date serialization?

Example:
```
"type": "string",
"format": "date-time"
```

**Comment by rigolepe** [comment]
Yes, it's on de backlog, https://github.com/atomicbits/scraml/issues/35, but probably not for the very near future, I'm afraid. RAML 1.0 takes priority over all larger and non-bug issues now.

**Comment by gurumeditator** [comment]
Sorry for the duplicate.

**Comment by rigolepe** [comment]
No worries.
