### ISSUE TITLE
External Reference from Nested Schema

### ISSUE THREAD

**Issue by gurumeditator** [atomicbits/scraml#70]
I am having an issue referencing an external schema from inside a nested schema:

```
failed: key not found: RootId([EXTERNAL_SCHEMA])
```

```
   "connectionItem":{
      "id":"#/connectionItem",
      "type":"object",
      "properties":{
         "data":{
            "$ref":"#connection"
         },
         "messages":{
            "$ref":"messages.json"
         }
   }
```

where messages.json is the external ref (contained in the same folder) and connectionItem is the fragment. I have also tried the full URL for the external ref.

Is this supported?

**Comment by rigolepe** [comment]
This should work, indeed. Could you give a little bit more of the surrounding json-schema? 

"$ref": "messages.json" should resolve relatively to the first absolute root "id" you meet when navigating upwards.

**Comment by gurumeditator** [comment]
Thanks Peter. Here is the schema. I have omitted the parameters:

Directory structure
schemas
--connections.json
--messages.json

**connections.json**
```
{
   "$schema":"http://json-schema.org/draft-04/schema",
   "id":"http://example.com/schema/connectionsInline.json#",
   "type":"object",
   "connection":{
      "id":"#/connection",
      "properties":{
...
      },
      "type":"object"
   },
   "connectionItem":{
      "id":"#/connectionItem",
      "type":"object",
      "properties":{
         "data":{
            "$ref":"#connection"
         },
         "messages":{
            "$ref":"messages.json"
         }
   },
  "connectionCollection":{
      "id":"#/connectionCollection",
      "type":"object",
      "properties":{
         "data":{
            "type":"array",
            "items":{
               "$ref":"#connection"
            }
         },
         "messages":{
            "$ref":"messages.json"
         }
   }
}
```

**messages.json**
```
{
   "$schema":"http://json-schema.org/draft-04/schema",
   "id":"http://example.com/schema/messages.json",
   "type":"array",
   "items":{
      "type":"object",
      "properties":{
         ...
      }
   }
}
```

**Comment by rigolepe** [comment]
Which version of scraml are you on? I tested your schema's without hitting errors. The last version is 0.4.14.

**Comment by gurumeditator** [comment]
I was using 0.4.13. Has 0.4.14 been published to a repository?

```
 The POM for io.atomicbits:scraml-maven-plugin:jar:0.4.14 is missing, no dependency information available
```
Is there an an additional repo I need to add?
```
https://repository-master.mulesoft.org/nexus/content/repositories/releases/
https://repo.maven.apache.org/maven2
https://maven.java.net/content/groups/public/
```

**Comment by rigolepe** [comment]
Version 0.4.13 is ok, it's recent enough and 0.4.14 has no changes that may affect parsing json-schema.  The maven repo is the default maven repository, so it's strange that you can't resolve it (http://repo1.maven.org/maven2/io/atomicbits/). 

I can't pinpoint the key not found problem that you have. I'll look into it again tomorrow.

**Comment by gurumeditator** [comment]
Thanks Peter. Let me know if you find anything or if I can provide more information. Appreciate all of your hard work.

**Comment by rigolepe** [comment]
No worries, I want to find where it goes wrong. I'm busy with a cloud migration for a client this week and some unexpected things came up, so I'll have to look into this later. Maybe this weekend.

**Comment by gurumeditator** [comment]
I believe I figured out the issue. The schema was being included in the RAML specification as:
```
   - !include schemas/diameter/connection.json
```

I was able to get past the error by including the schema using:
```
   - connection: !include schemas/diameter/connection.json
```
